version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

  liquibase:
    image: liquibase/liquibase:4
    container_name: liquibase
    environment:
      LIQUIBASE_URL: jdbc:postgresql://postgres:5432/postgres
      LIQUIBASE_USERNAME: postgres
      LIQUIBASE_PASSWORD: 123
      LIQUIBASE_CHANGELOG: db/changelog/db.changelog-master.xml
    depends_on:
      - postgres
    entrypoint: ["liquibase", "--changeLogFile=db/changelog/db.changelog-master.xml", "update"]

  app:
    build: .
    container_name: springbootapp
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - liquibase
    ports:
      - "8080:8080"